name: proyecto_aprender_jugando
description: "Proyecto Final de Ciclo Aprender Jugando"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  uuid: ^4.2.0
  image: ^4.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_estrella.png"

flutter:
  assets:
    - assets/images/avatar01.png
    - assets/images/avatar02.png
    - assets/images/splash_screen.png
    - assets/images/logo_estrella.png
    - assets/images/fondo_menus.png
    - assets/images/fondo_juegos.png
    - assets/images/logo_puzzle.png
    - assets/images/logo_mates.png
    - assets/images/logo_colores.png
    - assets/images/logo_letras.png
    - assets/images/logo_parejas.png
    - assets/images/arbol.png
    - assets/images/calabaza.png
    - assets/images/cerdo.png
    - assets/images/cesta.png
    - assets/images/coche.png
    - assets/images/flor.png
    - assets/images/fresa.png
    - assets/images/mundo.png
    - assets/images/oso.png
    - assets/images/pajaro.png
    - assets/images/poyo.png
    - assets/images/zanahoria.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
  uses-material-design: true